#!/usr/bin/env node

import yargs from "yargs/yargs"
import { hideBin } from "yargs/helpers"
import path from "path"
import fs from "fs/promises"
import execa from "execa"
import { getTreeFromSQL, treeToDirectory, loadStructureSQL } from "./"

const argv = yargs(hideBin(process.argv))
  .command("dump-to-dir", "Dump database structure into directory", (yargs) =>
    yargs
      .positional("dir", {
        describe: "Target Directory to dump to (will be deleted/recreated)",
      })
      .options({
        header: {
          desc: "Header at top of generated sql files",
          default: "Generated by pgtui",
        },
      })
  )
  .options({
    host: { desc: "Postgres Host" },
    password: { desc: "Postgres Password" },
    user: { desc: "Postgres User" },
    port: { desc: "Postgres Port" },
    database: { desc: "Postgres Database" },
  })
  .showHelpOnFail(true)
  .demandCommand().argv

const commandMap = {
  async "dump-to-dir"(yargs) {
    const [, targetDir] = yargs._
    const content = await loadStructureSQL(yargs)
    console.log("tree to directory...")
    await treeToDirectory(getTreeFromSQL(content), targetDir, yargs)
  },
}

async function main() {
  const [cmd] = (await argv)._

  if (!commandMap[cmd]) throw new Error(`Command not found "${cmd}"`)

  await commandMap[cmd](yargs)
}

console.log(argv)
